<a href="https://colab.research.google.com/github/guihensn/investment-studies/blob/main/08_An%C3%A1lise_de_Empresas_com_Python_no_Google_Colab_Python_para_Investimentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ricos pelo Acaso

Link para o vídeo: https://youtu.be/e_ZRDG4F4ZA

# Importando Bibliotecas

In [1]:
import numpy as np
import pandas as pd
import string
import warnings
warnings.filterwarnings('ignore')

import requests

# Obtendo e tratando os dados

In [2]:
url = 'http://www.fundamentus.com.br/resultado.php'

In [3]:
header = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
 }

r = requests.get(url, headers=header)

In [4]:
df = pd.read_html(r.text,  decimal=',', thousands='.')[0]

In [17]:
df.columns

Index(['Papel', 'Cotação', 'P/L', 'P/VP', 'PSR', 'Div.Yield', 'P/Ativo',
       'P/Cap.Giro', 'P/EBIT', 'P/Ativ Circ.Liq', 'EV/EBIT', 'EV/EBITDA',
       'Mrg Ebit', 'Mrg. Líq.', 'Liq. Corr.', 'ROIC', 'ROE', 'Liq.2meses',
       'Patrim. Líq', 'Dív.Brut/ Patrim.', 'Cresc. Rec.5a'],
      dtype='object')

In [28]:
for coluna in ['Div.Yield', 'Mrg Ebit', 'Mrg. Líq.', 'ROIC', 'ROE', 'Cresc. Rec.5a']:
    df[coluna] = df[coluna].astype(str)
    df[coluna] = df[coluna].str.replace('.', '')
    df[coluna] = df[coluna].str.replace(',', '.')
    df[coluna] = df[coluna].str.rstrip('%').astype('float') / 100

# Analisando os dados

In [30]:
df = df[df['Liq.2meses'] > 1000000]

In [31]:
ranking = pd.DataFrame()
ranking['pos'] = range(1,151)
ranking['EV/EBIT'] = df[ df['EV/EBIT'] > 0 ].sort_values(by=['EV/EBIT'])['Papel'][:150].values
ranking['ROIC'] = df.sort_values(by=['ROIC'], ascending=False)['Papel'][:150].values

In [32]:
ranking

     pos EV/EBIT   ROIC
0      1   PSSA3  JPSA3
1      2   WIZC3  RAIZ4
2      3   PCAR3  TGMA3
3      4   GOAU4  CURY3
4      5   SYNE3  KEPL3
..   ...     ...    ...
145  146   AZZA3  ELET6
146  147   RENT3  JHSF3
147  148   SMFT3  EZTC3
148  149   ENEV3  MTRE3
149  150   CVCB3  BRAV3

[150 rows x 3 columns]

In [34]:
a = ranking.pivot_table(columns='EV/EBIT', values='pos')

In [35]:
b = ranking.pivot_table(columns='ROIC', values='pos')

In [36]:
t = pd.concat([a,b])
t

,ABEV3,AGRO3,ALOS3,ALUP11,ANIM3,ARML3,ASAI3,AURA33,AZUL4,AZZA3,...,FRAS3,JPSA3,LOGG3,LOGN3,ORVR3,PNVL3,RADL3,RAIZ4,SMTO3,SRNA3
pos,113.0,110.0,31.0,67.0,24.0,64.0,13.0,80.0,119.0,146.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pos,NaN,105.0,144.0,103.0,39.0,76.0,58.0,50.0,62.0,24.0,...,61.0,1.0,30.0,128.0,13.0,136.0,74.0,2.0,23.0,139.0

In [38]:
rank = t.dropna(axis=1).sum()
rank

AGRO3     215.0
ALOS3     175.0
ALUP11    170.0
ANIM3      63.0
ARML3     140.0
          ...
VIVA3     152.0
VIVT3     266.0
VULC3     145.0
WIZC3      51.0
YDUQ3     208.0
Length: 132, dtype: float64

In [39]:
rank.sort_values()[:15]

KEPL3    23.0
COGN3    32.0
PLPL3    32.0
EVEN3    39.0
QUAL3    41.0
CMIG4    44.0
PSSA3    49.0
PCAR3    49.0
WIZC3    51.0
CSED3    57.0
TGMA3    59.0
POMO3    59.0
CMIN3    61.0
SEER3    62.0
ANIM3    63.0
dtype: float64